version: "3.8"

services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8081:8081"
    volumes:
      - ./BE:/srv
      - /srv/node_modules
    environment:
      - PYTHONPATH=/srv
    networks:
      - app-network
    command: uvicorn src.main:application --host 0.0.0.0 --port 8081 --reload

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./FE:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm run dev"

networks:
  app-network:
    driver: bridge
